name: Terraform CI

# when we git push successfully, this will run 
on:
 pull_request:
   branches:
     - main

# declare the running agent
jobs:
 terraform-ci:
   runs-on: ubuntu-latest

   steps:

  ##setup
   - name: Checkout repository
     uses: actions/checkout@v2

  #aws configure
   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-1 # or hardcode us-east-1

  #install terraform
   - name: Set up Terraform
     uses: hashicorp/setup-terraform@v1

  #terraform init
   - name: Initialize Terraform
     run: terraform init

  #terraform fmt
   - name: Terraform Prettify
     run: terraform fmt
     
  #terrafrom plan
   - name: Terraform Plan
     run: terraform plan

  #terraform validate
   - name: Terraform Validate
     run: terraform validate
